[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev:vite"
  port = 8888
  targetPort = 5173
  autoLaunch = false
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
