// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqugzlobgmkrugdzvpdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxdWd6bG9iZ21rcnVnZHp2cGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTc5MzMsImV4cCI6MjA2ODM3MzkzM30.P-WtIt6TQ4pqxeey5TkIDISH6-KndRJorC7y86hM2Wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});