name: Create/Delete Branch for Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    name: Setup
    outputs:
      branch: ${{ steps.branch_name.outputs.current_branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

  create_neon_branch:
    name: Create Neon Branch
    needs: setup
    if: >-
      ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened') }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Neon Branch
        id: create
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
      
      - name: Run Database Migrations
        run: |
          echo "Database URL: ${{ steps.create.outputs.db_url_pooled }}"
          # Add your migration commands here when ready
          # npm run db:migrate
        env:
          DATABASE_URL: "${{ steps.create.outputs.db_url_pooled }}"
      
      - name: Log Database Info
        run: |
          echo "🚀 Preview Environment Ready!"
          echo "Database Branch: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}"
          echo "Database URL: Available in Netlify deploy preview environment"
          echo "Note: This preview database will be automatically deleted when the PR is closed."

  delete_neon_branch:
    name: Delete Neon Branch
    needs: setup
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
          
      - name: Log Cleanup Info
        run: |
          echo "🧹 Preview Environment Cleaned Up"
          echo "The preview database branch preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }} has been deleted."
          echo "Thank you for your contribution! 🎉"
